# Generated by Django 4.2.3 on 2023-08-01 13:13

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TeamPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_time', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='created time')),
                ('updated_time', models.DateTimeField(auto_now=True, verbose_name='updated time')),
                ('is_active', models.BooleanField(default=True, verbose_name='is active')),
                ('name', models.CharField(max_length=255, verbose_name='name')),
                ('price', models.DecimalField(decimal_places=4, max_digits=12, verbose_name='price')),
                ('description', models.TextField(blank=True, verbose_name='description')),
                ('max_leads', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)], verbose_name='maximum leads')),
                ('max_clients', models.IntegerField(verbose_name='maximum clients')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
