# Generated by Django 4.2.3 on 2023-08-07 08:42

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_remove_client_team_remove_lead_team'),
        ('team', '0003_team_plan'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='team',
            name='members',
        ),
        migrations.AddField(
            model_name='team',
            name='client',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='team_clients', to='user.client', verbose_name='clients'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='team',
            name='lead',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='team_leads', to='user.lead', verbose_name='leads'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='teamplan',
            name='max_clients',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='maximum clients'),
        ),
        migrations.AlterField(
            model_name='teamplan',
            name='max_leads',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='maximum leads'),
        ),
    ]
