# Generated by Django 4.2.3 on 2023-08-07 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_remove_client_team_remove_lead_team'),
        ('team', '0004_remove_team_members_team_client_team_lead_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='team',
            name='client',
        ),
        migrations.RemoveField(
            model_name='team',
            name='lead',
        ),
        migrations.AddField(
            model_name='team',
            name='client',
            field=models.ManyToManyField(related_name='team_clients', to='user.client', verbose_name='clients'),
        ),
        migrations.AddField(
            model_name='team',
            name='lead',
            field=models.ManyToManyField(related_name='team_leads', to='user.lead', verbose_name='leads'),
        ),
    ]
