# Generated by Django 4.2.3 on 2023-07-30 12:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0001_initial'),
        ('user', '0003_lead_converted_to_client_alter_lead_priority_client'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='team',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='clients', to='team.team', verbose_name='team'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='lead',
            name='team',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='leads', to='team.team', verbose_name='team'),
            preserve_default=False,
        ),
    ]
