# Generated by Django 4.2.3 on 2023-08-07 08:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_client_team_lead_team'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='team',
        ),
        migrations.RemoveField(
            model_name='lead',
            name='team',
        ),
    ]
